// <auto-generated />
using BulkyWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulkyWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250604200202_SeedUserTable")]
    partial class SeedUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulkyWeb.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Action",
                            DisplayOrder = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Comedy",
                            DisplayOrder = 3
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Romantic",
                            DisplayOrder = 7
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "War",
                            DisplayOrder = 4
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Anime",
                            DisplayOrder = 2
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Detective",
                            DisplayOrder = 5
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Documentary",
                            DisplayOrder = 6
                        });
                });

            modelBuilder.Entity("BulkyWeb.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "Johny@email.com",
                            UserName = "Johny"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "Lussia@email.com",
                            UserName = "Lussie"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "Ritta@email.com",
                            UserName = "Ritta"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "Josh@email.com",
                            UserName = "Josh"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "Sophie@email.com",
                            UserName = "Sophie"
                        },
                        new
                        {
                            UserId = 6,
                            Email = "Steve@email.com",
                            UserName = "Steve"
                        },
                        new
                        {
                            UserId = 7,
                            Email = "Diana@email.com",
                            UserName = "Diana"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
